name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            ${{ runner.os }}-
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Update gh-pages branch
        run: |
          cd $GITHUB_WORKSPACE
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git fetch origin gh-pages
          git checkout -b gh-pages origin/gh-pages
          git rm -r index.html bundle.js bundle.js.LICENSE.txt css
          mv dist/* .
          git add .
          git commit -m "Update github pages from ${{ github.sha }}"
          git push -u origin gh-pages
